# https://taskfile.dev/docs/guide
# https://taskfile.dev/reference/templating/
version: '3'
vars:
  CLI_PATH: req_client
  
tasks:
  default: mix test
  sh: iex --erl "-kernel shell_history enabled" -S mix
  fmt: mix format

  test.all: mix test --include try --include external

  build:
    aliases: ["b"] 
    cmds:
    - mix escript.build --force

  install:
    aliases: ["i"]
    deps: ["build"]
    cmds:
    - mix escript.install {{.CLI_PATH}} --force
  hex.i: mix escript.install hex req_client --force
  gi: mix escript.install github cao7113/req_client --force

  bench: |
    url=http://localhost:4000/api/delay/1000/ms
    mix run ./run/benchmark.exs $url -r 1
    # [mint: 1187, req: 1187, httpc: 1233]
    mix run ./run/benchmark.exs $url -r 10
    # [mint: 1246, req: 1246, httpc: 1312]
    mix run ./run/benchmark.exs $url -r 50
    # [req: 1629, mint: 1644, httpc: 1647]
    time curl $url

  ## Git ops
  ops.up: mix git_ops.release --yes && git push --follow-tags
  prj.info: mix git_ops.project_info
  ops.init: mix git_ops.release --initial

  setup: |
    mix deps.get